on: 
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create version Folder
        run: mkdir -p v1.10.0/

      - name: Rename the file
        run: mv VersaNote-v1.10.0.msi v1.10.0/VersaNote.msi
      
      - name: List the tree structure before upload
        run: ls -R
       
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_KEY }}
         timeout: 5m
         source: v1.10.0/
         target: /var/www/html/wp-content/uploads/v1.10.012
