on: 
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Rename the file
        run: mv VersaNote-v1.10.0.msi VersaNote.msi
      
      - name: List the tree structure before upload
        run: ls -R
       
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_KEY }}
         timeout: 5m
         source: VersaNote.msi
         target: /root/v1.10.0
